"""Evolve to POS Credit

Revision ID: 239832a01773
Revises: fda4d956d6a5
Create Date: 2026-04-25 10:54:02.806150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '239832a01773'
down_revision = 'fda4d956d6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factura_credito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('total_factura', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo_pendiente', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente_cartera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_factura_credito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['factura_credito.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 1. DROP CONSTRAINTS FIRST
    with op.batch_alter_table('abono_credito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factura_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('abono_credito_compra_id_fkey', type_='foreignkey')
        
    with op.batch_alter_table('acuerdo_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factura_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('acuerdo_pago_compra_id_fkey', type_='foreignkey')

    # 2. NOW DROP THE TABLE
    op.drop_table('compra_credito')
    
    # 3. COMPLETE OTHER CHANGES
    op.create_table('movimiento_caja_cartera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('fecha_movimiento', sa.DateTime(), nullable=True),
    sa.Column('abono_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abono_id'], ['abono_credito.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('abono_credito', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'factura_credito', ['factura_id'], ['id'])
        batch_op.drop_column('compra_id')
        batch_op.alter_column('factura_id', nullable=False)

    with op.batch_alter_table('acuerdo_pago', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'factura_credito', ['factura_id'], ['id'])
        batch_op.drop_column('compra_id')
        batch_op.alter_column('factura_id', nullable=False)

    # Clean up other tables
    with op.batch_alter_table('price_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_approvals_estado'))
    op.drop_table('price_approvals')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('clientes_creado_por_id_fkey'), type_='foreignkey')
        batch_op.drop_column('creado_por_id')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consecutivo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cliente_nombre', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # Simplificado ya que es una migración mayor
    pass
