"""Refactor product to jsonb and categories

Revision ID: 6dffb71ba7ee
Revises: 33a02b7344bf
Create Date: 2026-05-07 23:22:40.123921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6dffb71ba7ee'
down_revision = '33a02b7344bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('atributos')
        batch_op.drop_column('categoria_id')

    op.drop_table('categories')
    # ### end Alembic commands ###
